### ISSUE TITLE
Windows Factom Enterprise Wallet Download

### ISSUE THREAD

**Issue by nrprivae** [FactomProject/distribution#2]
All the download links to install a Factom wallet on Windows seem to be down.
They were fine maybe 3 weeks ago, but been down for a full week.
Anyone any ideas ?  Bit poor really :(
Thanks

**Comment by nrprivae** [comment]
I guess time to sell my Factom.....

**Comment by carryforward** [comment]
Thanks for the note.  I have added a link to the previous version, which should work fine for client side operations.  

I did notice my ad blocker complaining about github's redirection, but checking the hashes should satisfy any fears of corrupt downloads.
